"""Write docs/TEST_COUNT.txt from ``pytest --collect-only``."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "TEST_COUNT.txt"
COLLECT_RE = re.compile(r"(\d+) tests collected")


def collected_count() -> int:
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    blob = (proc.stdout or "") + "\n" + (proc.stderr or "")
    match = COLLECT_RE.search(blob)
    if match is None:
        sys.stderr.write(blob)
        raise SystemExit("pytest --collect-only did not print 'N tests collected'")
    return int(match.group(1))


def render(count: int) -> str:
    return (
        "# Generated by scripts/export_test_count.py. Do not edit by hand.\n"
        f"collected={count}\n"
        "command=python -m pytest --collect-only -q\n"
    )


def main() -> int:
    count = collected_count()
    OUT.write_text(render(count), encoding="utf-8", newline="\n")
    sys.stdout.write(f"{count}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
